### PR TITLE
Include entry layer name in PTX cache key

### PR DESCRIPTION
**Pull request by chellmuth**
## Description

The ptx cache key introduced in #1938 didn't include a shader's entry layer name in its cache key. The direct callable function generated during llvm construction includes this layer name, so we could get false positive cache hits when two identical networks with matching group names had different entry layer names. The end result is an optix compilation error. This PR extends the cache key to handle this scenario.

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project. If I haven't
  already run clang-format v17 before submitting, I definitely will look at
  the CI test that runs clang-format and fix anything that it highlights as
  being nonconforming.

### CODE REVIEW

**Comment by lgritz** [comment]
I don't think the CI failures here are related to this PR -- they appear to be (perhaps momentary?) failures to download the Intel compilers. I'm rerunning the failed tests now to see if it's fixed.

**Review by lgritz — APPROVED** [review]
LGTM
